blueprint:
  name: ZHA - Osram Smart+ Switch Mini
  description: Automate your Osram Smart+ Switch Mini Scene Switch using ZHA events.
  domain: automation
  input:
    remote:
      name: Osram Smart+ Switch Mini Scene Switch
      description: Osram Smart+ Switch Mini Scene Switch to use
      selector:
        device:
          integration: zha
          manufacturer: OSRAM
          model: Lightify Switch Mini
          multiple: false
    up_button_short_press:
      name: Up button short press
      description: Action to run on up button short press
      default: []
      selector:
        action: {}
    up_button_long_press:
      name: Up button long press
      description: Action to run on up button long press
      default: []
      selector:
        action: {}
    middle_button_short_press:
      name: Middle button short press
      description: Action to run on middle button short press
      default: []
      selector:
        action: {}
    middle_button_long_press:
      name: Middle button long press
      description: Action to run on middle button long press
      default: []
      selector:
        action: {}
    down_button_short_press:
      name: Down button short press
      description: Action to run on down button short press
      default: []
      selector:
        action: {}
    down_button_long_press:
      name: Down button long press
      description: Action to run on down button long press
      default: []
      selector:
        action: {}
  source_url: https://raw.githubusercontent.com/jclsn/osram-smart-switch-mini-blueprint-zha/main/osram-smart-switch-mini-zha.yml

mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
action:
  - variables:
      endpoint_id: '{{ trigger.event.data.endpoint_id }}'
      command: '{{ trigger.event.data.command }}'
  - choose:
    - conditions: '{{ endpoint_id == 1 }}'
      sequence:
      - choose:
        - conditions: '{{ command == on }}'
          sequence: !input up_button_short_press
        - conditions: '{{ command == move_with_on_off }}'
          sequence: !input up_button_long_press
    - conditions: '{{ endpoint_id == 2 }}'
      sequence:
      - choose:
        - conditions: '{{ command == off }}'
          sequence: !input down_button_short_press
        - conditions: '{{ command == move }}'
          sequence: !input down_button_long_press
    - conditions: '{{ endpoint_id == 3 }}'
      sequence:
      - choose:
        - conditions: '{{ command == move_to_level_with_on_off }}'
          sequence: !input middle_button_short_press
        - conditions: '{{ command == move_hue }}'
          sequence: !input middle_button_long_press
